config/routes.rb
Seventydegrees::Application.routes.draw do
  
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'
  get 'contact' => 'pages#contact'
  root :to => 'pages#home'
  
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		Home
		About
		FAQ
		Contact
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Seventy Degrees</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
		<ul class="nav pull-right">
        	<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "FAQ", faq_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>	
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Seventy Degrees</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
			<%= yield %>
			<%= render 'layouts/footer'%>
		</div>	
	</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<div class="hero-unit">
	<h1>Seventy Degrees app</h1>
	<p>Where should I go now?</p>
</div>

<div class="row">
  <div class="span5">
  	<h2> this is where the calendar goes </h2>
  </div>
  <div class="span5">
  </div>
  <div class="span2">
  	<h3> this is where the ads go </h3>
  </div>
</div>

<div class="row">
  <div class="span5">
	 	<h2> this is where the slider goes </h2>
  </div>
  <div class="span5">
  	<%= link_to "GO!", "#", class: "btn btn-large btn-primary btn-block" %>
  </div>
  <div class="span2">
  	<h3> this is where the ads go </h3>
  </div>
</div>

<div class="row">
  <div class="span5">
  </div>
	<div class="span3">
  	<h3> this is where the destinations go </h3>
  </div>
  <div class="span2">
  	<h3> this is where something else goes </h3>
  </div>
  <div class="span2">
  	<h3> this is where the ads go </h3>
  </div>
</div>